import pygame


# main
REFRESH_PER_SECOND = 60
NUMBER_OF_FLOORS = 50
NUMBER_OF_ELEVATORS = 3

# images paths
ELV_ING_PATH = "pic/elv.png"
FLOOR_IMG_PATH = "pic/floor.jpg"
DING_FILE_PATH = "ding.mp3"

# sizes
FLOOR_WIDTH, FLOOR_HEIGHT = 150, 80
ELEVATOR_WIDTH, ELEVATOR_HEIGHT = 65, 70
BUTTON_SIZE = 20
FONT_SIZE = 30
SCREEN_WIDTH, SCREEN_HEIGHT = max(500, 280 + ELEVATOR_WIDTH * NUMBER_OF_ELEVATORS), 650
MARGIN = 8
ENVIRONMENT_WIDTH, ENVIRONMENT_HEIGHT = SCREEN_WIDTH, max(SCREEN_HEIGHT, 3 * MARGIN + NUMBER_OF_FLOORS * FLOOR_HEIGHT)
RESET_SIZE = 30
FLOOR_SPACER_HEIGHT = 7

# positions
GROUND_FLOOR_POS = (MARGIN, ENVIRONMENT_HEIGHT - FLOOR_HEIGHT - MARGIN)
BASE_BUTTON_POS = (MARGIN + FLOOR_WIDTH // 2, ENVIRONMENT_HEIGHT - FLOOR_HEIGHT // 2 - MARGIN)
BASE_ELEVATOR_POS = (MARGIN + FLOOR_WIDTH, ENVIRONMENT_HEIGHT - ELEVATOR_HEIGHT - MARGIN)
RESET_BUTTON_POS = (SCREEN_WIDTH - 40, 40)

# colors
WHITE = 200, 200, 255
GRAY = 100, 100, 100
GRAY_FOR_OVER = 120, 120, 120
GRAY_FOR_BUTTON_BORDER = 180, 180, 180
BLACK = 0, 0, 0
RED = 255, 20, 20

#elevator
ELEVATOR_VELOCITY = 160  # P/S
