import pygame

# users input
NUMBER_OF_FLOORS = 15
NUMBER_OF_ELEVATORS = 3

# general
ELEVATOR_VELOCITY = 160  # P/S

# files paths
ELV_ING_PATH = "pic/elv.png"
ACTIVE_ELV_ING_PATH = "pic/active_elv.png"
FLOOR_IMG_PATH = "pic/floor.jpg"
DING_FILE_PATH = "sound/ding.mp3"

# sizes
ELEVATOR_WIDTH, ELEVATOR_HEIGHT = 65, 70
FLOOR_WIDTH, FLOOR_HEIGHT = 150, 80
FLOOR_SPACER_HEIGHT = 7
TIMER_BG_WIDTH, TIMER_BG_HEIGHT = 90, 40
BUTTON_SIZE = 20
RESET_BUTTON_SIZE = 30
FONT_SIZE = 30
MARGIN = 8
SCREEN_WIDTH, SCREEN_HEIGHT = (max(500, 280 + ELEVATOR_WIDTH * NUMBER_OF_ELEVATORS), 650)
ENVIRONMENT_WIDTH, ENVIRONMENT_HEIGHT = (SCREEN_WIDTH, max(SCREEN_HEIGHT, 3 * MARGIN + NUMBER_OF_FLOORS * FLOOR_HEIGHT))

# positions
GROUND_FLOOR_POS_X, GROUND_FLOOR_POS_Y = (MARGIN, ENVIRONMENT_HEIGHT - FLOOR_HEIGHT - MARGIN)
BASE_BUTTON_POS_X, BASE_BUTTON_POS_Y = (MARGIN + FLOOR_WIDTH // 2, ENVIRONMENT_HEIGHT - FLOOR_HEIGHT // 2 - MARGIN)
TIMER_POS_ON_FLOOR_X, TIMER_POS_ON_FLOOR_Y = 25, 32
BASE_ELEVATOR_POS_X, BASE_ELEVATOR_POS_Y = (MARGIN + FLOOR_WIDTH, ENVIRONMENT_HEIGHT - ELEVATOR_HEIGHT - MARGIN)
RESET_BUTTON_POS = (SCREEN_WIDTH - 40, 40)

# colors
WHITE = 230, 230, 230
GRAY = 100, 100, 100
GRAY_FOR_OVER = 120, 120, 120
GRAY_FOR_BUTTON_BORDER = 180, 180, 180
BLACK = 0, 0, 0
RED = 255, 20, 20
